config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'upload', to: 'icds#upload'
  post 'process_file', to: 'icds#process_file'
  get 'search', to: 'icds#search'

  resources :icds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/icd.rb
class Icd < ApplicationRecord
  validates :code, presence: true, length: {minimum:1, maximum:10}
  validates :description, presence: true, length: {minimum:1, maximum:100}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/icds_controller.rb
class IcdsController < ApplicationController
  before_action :set_icd, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @icds = Icd.all
  end

  def new
  end

  def create
    @icd = Icd.new(icd_params)
  
    if @icd.save
      flash[:notice] = "ICD Record created successfully"
      redirect_to @icd
    else
      render 'new'
    end    
  end

  def edit
  end

  def update
    if @icd.update(icd_params)
      flash[:notice] = "ICD Record updated sucessfully"
      redirect_to @icd
    else
      render 'edit'
    end
  end

  def destroy
    @icd.destroy
    redirect_to icds_path
  end

  def upload
  end

  def process_file
    uploaded_file = params[:filename]
    full_filename_with_path = Rails.root.join('public', 'uploads', uploaded_file.original_filename)
    if uploaded_file != nil
      # render html: full_filename_with_path
      File.open(full_filename_with_path, 'wb') do |f|
        f.write(uploaded_file.read)
      end
    end

    if(params[:type] == 'new')
      fields = [
        { name: 'code', position: 0..7 },
        { name: 'description', position: 9..-1 }
      ]   
      FixedWidthFileParser.parse(full_filename_with_path.to_s, fields, force_utf8_encoding: false) do |row| 
        puts "ICD Code: \"#{row[:code]}\" & Description: \"#{row[:description]}\""
        icd = Icd.new
        icd.code = row[:code]
        icd.description = row[:description]
        icd.save
      end
    else
      fields = [
        { name: 'method', position: 0..12 },
        { name: 'code', position: 14..20 },
        { name: 'description', position: 21..-1 }
      ]   
      FixedWidthFileParser.parse(full_filename_with_path.to_s, fields, force_utf8_encoding: false) do |row| 
        puts "ICD Code: \"#{row[:code]}\" & Description: \"#{row[:description]}\""

        if row[:method].downcase.include?("add:")
          icd = Icd.new
          icd.code = row[:code]
          icd.description = row[:description]
          icd.save
        elsif row[:method].downcase.include?("delete:")
          #TODO remove the matching code from db
        elsif row[:method].downcase.include?("revise from:")
          #TODO read next line to collect data of revise to
        end
      end
    end

    flash[:notice] = "ICD File uploaded sucessfully"
    redirect_to icds_path

  end

  def search
  end

  private
  def set_icd
    @icd = Icd.find(params[:id])
  end

  def icd_params
    params.require(:icd).permit(:code, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/icds/edit.html.erb
<div class="container">
  <h1>Edit an ICD Record</h1>

  <%= render 'shared/errors' %>

  <%= form_with(model: @icd, local: true)  do |f| %>
    <p>
      <%= f.label :code %> <br>
      <%= f.text_field :code %>
    </p>

    <p>
      <%= f.label :description %> <br>
      <%= f.text_field :description %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>

  <%= link_to 'Cancel Edit & Return to ICD Listing', icds_path %>
</div>

app/views/icds/index.html.erb
<div class="container">
<h1>ICD Listing</h1>

<table class="table">
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @icds.each do |icd| %>
    <tr>
      <td><%= icd.code %></td>
      <td><%= icd.description %></td>
      <td><a href=<%= icd_path(icd) %> class="btn btn-outline-success">View</a></td>
      <td><a href=<%= edit_icd_path(icd) %> class="btn btn-outline-info">Edit</a></td>
      <td><%= link_to "Delete", icd_path(icd), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %></td>
      <td><small>Created <%= time_ago_in_words(icd.created_at) %> ago </small></td>
      <td><small>Modifed <%= time_ago_in_words(icd.updated_at) %> ago </small></td>
     </tr>
    <% end %>
  </tbody>
</table>

<p> 
  <%= link_to "Add ICD Code", new_icd_path %> | 
  <%= link_to "Upload from file", upload_path %> | 
  <%= link_to "Search", search_path %>
</p>

</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "My Company", "http://www.google.com", class: "text-white" %></small>
  </div>
</footer>

app/views/icds/new.html.erb
<div class="container">
  <h1>Create a New ICD Record</h1>

  <%= render 'shared/errors' %>

  <%= form_with scope: :icd, url: icds_path, local: true do |f| %>
    <p>
      <%= f.label :code %> <br>
      <%= f.text_field :code %>
    </p>

    <p>
      <%= f.label :description %> <br>
      <%= f.text_field :description %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>

  <%= link_to 'Return to ICD Listing', icds_path %>
</div>

app/views/icds/search.html.erb
<div class="container">
  <h1>ICD Code Search</h1>

  <%= form_with url: "/search", method: :get do |form| %>
    <%= form.label :query, "Type keywords to search an appropriate ICD Code" %><br>
    <%= form.text_field :query %>
    <%= form.submit "Search" %>
  <% end %>

  <p><%= link_to 'Return to ICD Listing', icds_path %></p>
</div>

app/views/icds/show.html.erb
<h1>Selected ICD Record</h1>
<p><strong>Code: <%= @icd.code %></strong></p>
<p><strong>Description: <%= @icd.description %></strong></p>

<p>
  <%= link_to 'Edit', edit_icd_path(@icd) %> |
  <%= link_to 'Delete', icd_path(@icd), method: :delete, data: { confirm: "Are you sure?"} %> |
  <%= link_to 'Return to ICD Listing', icds_path %>
</p>

app/views/icds/upload.html.erb
<div class="container">
  <h1>Upload an ICD File</h1>

  <%= form_with url: "/process_file", multipart: true do |form| %>
    <%= form.file_field :filename %>
    <%= form.radio_button :type, "new" %>
    <%= form.label :type_new, "New File for Clean Upload" %>
    <%= form.radio_button :type, "update" %>
    <%= form.label :type_update, "Addendum File for Update" %>
    <%= form.submit "Upload" %>
  <% end %>

  <p><%= link_to 'Return to Article Listing', icds_path %></p>
</div>

app/views/layouts/_messages.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <% flash.each do |name, msg| %>
    <%= msg %>
  <% end %>

  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "ICD-REPO", root_path, class: "navbar-brand", id: "logo"%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "ICD Listing", icds_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ICD Repo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page-content">
  <div class="container">
    <h1>About page</h1>
  </div>
</div>

app/views/pages/home.html.erb
<div id="page-content">
<div class="container" id="home-container">
    <div class="jumbotron text-center text-blue">
        <h1 class="display-4">Hello, world!</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <p class="lead">
          <a class="btn btn-success btn-lg" href="#" role="button">Register</a>
        </p>
        <p>
        </p>
    </div>
</div>
</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "My Company | ", "http://www.google.com", class: "text-white" %>
    <%= link_to 'About', about_path , class: "text-white" %></small>
  </div>
</footer>

app/views/shared/_errors.html.erb
<% if @icd && @icd.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h4 class="alert-heading">The following errors prevented the ICD record to be Saved</h4>
      <ul>
      <% @icd.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      </ul>
    </div>
  <% end %>

  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
<% end %>